# Generated by tools/publish/scripts/homebrew_formula.py.
# Verified stable release inputs only.
class Usagestat < Formula
  desc "Scriptable CLI for local agent usage data"
  homepage "https://github.com/hashimkarim/usagestat"
  version "2.0.0"
  license "MIT"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0/usagestat-linux-aarch64.tar.gz"
      sha256 "c47a75eff2dc1c623bebb191008fded2db0647e0ce42893369b2945a07ad225a"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0/usagestat-linux-x86_64.tar.gz"
      sha256 "adabb318a816967f269dd1fded375ff594794e4d6d8d8d998691607843444c75"
    end
  end

  def install
    bin.install "usagestat", "usagestatd"
    (share/"usagestat").install "plugins", "LICENSE"
  end

  def caveats
    <<~EOS
      Enable login startup explicitly with: usagestat daemon enable
      The usagestat CLI owns startup registration; no brew services entry is installed.
      Before removing a managed installation, run: usagestat daemon unregister
      Configuration, history, and credentials are retained when uninstalling.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/usagestat --version")
    assert_match version.to_s, shell_output("#{bin}/usagestatd --version")
    ENV["USAGESTAT_CONFIG_DIR"] = (testpath/"config").to_s
    ENV["USAGESTAT_DATA_DIR"] = (testpath/"data").to_s
    providers = JSON.parse(shell_output("#{bin}/usagestat --json list"))
    assert providers.any? { |provider| provider["id"] == "codex" }
    assert_path_exists share/"usagestat/plugins/codex/plugin.json"
  end
end
