# Generated by tools/publish/scripts/homebrew_formula.py.
# Unsigned alpha release; desktop/minimum-system acceptance pending.
class UsagestatAlpha < Formula
  desc "Scriptable CLI for local agent usage data"
  homepage "https://github.com/hashimkarim/usagestat"
  version "2.0.0-alpha.4"
  license "MIT"
  on_linux do
    conflicts_with "usagestat", because: "both install the usagestat commands"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.4/usagestat-linux-aarch64.tar.gz"
      sha256 "1ed7e3dbc02a4b08b705ec4c1763e7e85b1f339768c3fa706445480c522ed02f"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.4/usagestat-linux-x86_64.tar.gz"
      sha256 "b8c064fa4002e5bef1de88e3da90d6e1b4c34bfcae029cd9e45a220667cfe2cc"
    end
  end

  on_macos do
    depends_on macos: :big_sur
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.4/usagestat-macos-aarch64.tar.gz"
      sha256 "b1901ad05491834eb2398fd62a67c36ae01b59d94b7a096035aa221b276c26c4"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.0-alpha.4/usagestat-macos-x86_64.tar.gz"
      sha256 "5405d0928abfd24b14ede0b6387427c6c95be615cfd36f774ae1d6e8a724e2ab"
    end
  end

  def install
    bin.install "usagestat", "usagestatd"
    (share/"usagestat").install "plugins", "LICENSE"
  end

  def caveats
    <<~EOS
      Enable login startup explicitly with: usagestat daemon enable
      The usagestat CLI owns startup registration; no brew services entry is installed.
      Before removing a managed installation, run: usagestat daemon unregister
      Configuration, history, and credentials are retained when uninstalling.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/usagestat --version")
    assert_match version.to_s, shell_output("#{bin}/usagestatd --version")
    ENV["USAGESTAT_CONFIG_DIR"] = (testpath/"config").to_s
    ENV["USAGESTAT_DATA_DIR"] = (testpath/"data").to_s
    providers = JSON.parse(shell_output("#{bin}/usagestat --json list"))
    assert providers.any? { |provider| provider["id"] == "codex" }
    assert_path_exists share/"usagestat/plugins/codex/plugin.json"
  end
end
