# Generated by tools/publish/scripts/homebrew_formula.py.
# Verified stable release inputs only.
class Usagestat < Formula
  desc "Scriptable CLI for local agent usage data"
  homepage "https://github.com/hashimkarim/usagestat"
  version "2.0.1"
  license "MIT"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.1/usagestat-linux-aarch64.tar.gz"
      sha256 "1c5ed1202ba6ea3e49db789a8e6db02cf73da75d3db290013602faccf07809ad"
    else
      url "https://github.com/hashimkarim/usagestat/releases/download/v2.0.1/usagestat-linux-x86_64.tar.gz"
      sha256 "14639690fcba5ed5038628bb6cfd684076e0c494fe6087fd6e01ddbddd299942"
    end
  end

  def install
    bin.install "usagestat", "usagestatd"
    (share/"usagestat").install "plugins", "LICENSE"
  end

  def caveats
    <<~EOS
      Enable login startup explicitly with: usagestat daemon enable
      The usagestat CLI owns startup registration; no brew services entry is installed.
      Before removing a managed installation, run: usagestat daemon unregister
      Configuration, history, and credentials are retained when uninstalling.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/usagestat --version")
    assert_match version.to_s, shell_output("#{bin}/usagestatd --version")
    ENV["USAGESTAT_CONFIG_DIR"] = (testpath/"config").to_s
    ENV["USAGESTAT_DATA_DIR"] = (testpath/"data").to_s
    providers = JSON.parse(shell_output("#{bin}/usagestat --json list"))
    assert providers.any? { |provider| provider["id"] == "codex" }
    assert_path_exists share/"usagestat/plugins/codex/plugin.json"
  end
end
